test('First Test', () => {
	throw new Error('First Error!')
})